branch-defaults:
  deploy/aws-eb:
    environment: crag-rag-pro
    group_suffix: null
environment-defaults:
  crag-rag-pro:
    branch: null
    repository: null
global:
  application_name: crag-rag-app
  branch: null
  default_ec2_keyname: null
  default_platform: Docker running on 64bit Amazon Linux 2023
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
